# Pytorch

## Matrisler (Matrices)

* matrisler, içerisinde değerler barındıran array'lerdir.
* array'ler herhangi bir neural network yapısını düşünürsek ilk aşama forward propagation yani prediction işleminin gerçekleştirildiği adım. prediction işlemini gerçekleştirdikten sonra loss değerine göre backward propagation ile parametrelerimizi güncelliyoruz ve böylece öğrenme işlemini gerçekleştiriyoruz.
* prediction matrislerin birbirleriyle çarpılıp toplanması sonucunda ortaya çıkan bir değerdir.
* backward propagation ile güncellediğimiz parametreler matristir.
* pytorch'da matrisler(array'ler), tensor olarak adlandırılabilir.
* 3 boyutlu tensor

In [1]:
# numpy array

In [2]:
import numpy as np

In [3]:
array = [[1,2,3],[4,5,6]] # liste
first_array = np.array(array) # 2x3 numpy array

In [4]:
print("Array Type: {}".format(type(first_array))) # type
print("Array Shape: {}".format(np.shape(first_array))) # shape

Array Type: <class 'numpy.ndarray'>
Array Shape: (2, 3)


In [5]:
print(first_array)

[[1 2 3]
 [4 5 6]]


In [6]:
np.array([
           [[1,3],[1,3],[1,3]],
           [[1,3],[1,3],[1,3]]
]).shape # 3 boyutlu

(2, 3, 2)

In [7]:
# pytorch array

In [8]:
import torch

In [9]:
array

[[1, 2, 3], [4, 5, 6]]

In [10]:
tensor = torch.Tensor(array)

In [11]:
print("Array Type: {}".format(tensor.type)) # type
print("Array Shape: {}".format(tensor.shape)) # shape

Array Type: <built-in method type of Tensor object at 0x111aeaa30>
Array Shape: torch.Size([2, 3])


In [12]:
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [13]:
# np.ones() = torch.ones()

# numpy ones
print("Numpy {}\n".format(np.ones((2,3))))

# pytorch ones
print(torch.ones((2,3)))

Numpy [[1. 1. 1.]
 [1. 1. 1.]]

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
# np.random.rand() = torch.rand()

# numpy random
print("Numpy {}\n".format(np.random.rand(2,3)))

# pytorch random
print(torch.rand(2,3))

Numpy [[0.57163786 0.88634858 0.1746615 ]
 [0.5555113  0.65201251 0.30745445]]

tensor([[0.1055, 0.9852, 0.4983],
        [0.7677, 0.4419, 0.0716]])


In [15]:
# numpy ve pytorch arasındaki geçişler

In [16]:
# random numpy array
array = np.random.rand(2,2)
print("{} {}\n".format(type(array), array)) # numpy

<class 'numpy.ndarray'> [[0.76602766 0.65106701]
 [0.70103679 0.05119881]]



In [17]:
# numpy -> tensor(pytorch)
from_numpy_to_tensor = torch.from_numpy(array)
print("{}\n".format(from_numpy_to_tensor)) # tensor

tensor([[0.7660, 0.6511],
        [0.7010, 0.0512]], dtype=torch.float64)



In [18]:
# tensor(pytorch) -> numpy
tensor = from_numpy_to_tensor
from_tensor_to_numpy = tensor.numpy()
print("{} {}\n".format(type(from_tensor_to_numpy), from_tensor_to_numpy)) # numpy

<class 'numpy.ndarray'> [[0.76602766 0.65106701]
 [0.70103679 0.05119881]]



## Basit Matematiksel İşlemler

* a ve b bir tensor ise:
  * yeniden boyutlandırma (reshape/resize): view()
  * torch.add(a,b) = a + b
  * a.sub(b) = a - b
  * torch.mul(a,b) = a * b
  * torch.div(a,b) = a/b
  * a.mean()
  * a.std()

In [19]:
# 3x3'lük birlerden oluşan bir tensor oluşturalım
tensor = torch.ones(3,3)
print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [20]:
# resize
# 3x3 tensor -> 9x1 vektör
print("{} - {}".format( tensor.view(9).shape, tensor.view(9) ))

torch.Size([9]) - tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [21]:
# toplama
print("Addition:\n{}".format( torch.add(tensor, tensor) ))

Addition:
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [22]:
# çıkartma
print("Subtraction:\n{}".format( tensor.sub(tensor) ))

Subtraction:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [23]:
# çarpma
print("Multiplication:\n{}".format( torch.mul(tensor, tensor) ))

Multiplication:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [24]:
# bölme
print("Division:\n{}".format( torch.div(tensor, tensor) ))

Division:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [25]:
# ortalama
tensor = torch.Tensor([1, 2, 3, 4, 5])
print("Mean: {}".format(tensor.mean()))

Mean: 3.0


In [26]:
# standart sapma
tensor = torch.Tensor([1, 2, 3, 4, 5])
print("std: {}".format(tensor.std()))

std: 1.5811388492584229


## Variables

* Variable'lar gradient'leri içerisinde depolayan, biriktiren yapılardır.
* neural network'te backward propagation'da gradient'ler hesaplanıyor
* bu gradient'leri hesapladığımızda bunları işleyebilmek için Variable veri tipini kullanacağız
* Variable aslında array'dir. tensor'de bir array'di.
* Variable ile tensor arasındaki fark Variable, türev aldığımızda yani gradient hesapladığımızda bu gradient'i içerisinde barındıran toplayan, biriktiren yapılardır.

#### backward propagation yani gradient

weight'ler ve bias'lar var. output layer'in sonucunda bir tane cost değeri ortaya çıkar ve cost değerlerinin toplanması sonucunda loss değeri elde edilir. weight'leri güncelleyebilmek için gradientleri hesaplarız. gradientler, loss'un weight'lere göre türevidir. pytorch'ta bu işlemi yapabilmek için bu değerlerin Variable isimli veri tipleri içerisinde depolanması gerekir.

Variable, gradient'leri hesaplamamıza yardım eder içerisinde gradient'leri biriktirir.

örneğin:
* y = x^2
* x = [2, 4]
* x sadece 2 veya 4 değerini alabiliyor
* y = [4, 16]
* o = (1/2)sum(y) = (1/2)*sum(x^2)
* o'nun x'e göre türevini (gradient) alacağız
* x -> y = x^2 -> o = (1/2)*sum(x^2)
* do/dx = (do/dy)*(dy/dx)
* o'nun x'e göre türevi x'dir. x değerlerini yerine koyduğumuzda x=2 ve x=4 gradient değerlerini elde ederiz

In [30]:
torch.ones(3)

tensor([1., 1., 1.])

In [31]:
from torch.autograd import Variable

# gradient hesaplanacağı için requires_grad = True
var = Variable(torch.ones(3), requires_grad = True)
var # Variable'ın tensor'den farkı türev almamıza yardımcı olur ve gradient'leri depolar

tensor([1., 1., 1.], requires_grad=True)

In [32]:
array = [2, 4]
tensor = torch.Tensor(array) # tensor
tensor

tensor([2., 4.])

In [33]:
x = Variable(tensor, requires_grad = True) # gradient'leri bulmak için x'i Variable yaptım
x # 2 ve 4 değerlerini içeren bir Variable

tensor([2., 4.], requires_grad=True)

In [34]:
# y = x^2
y = x**2 # 2 ve 4'ü yerine koyduğumuzda sonuç 4 ve 16 olur
print("y =", y)

y = tensor([ 4., 16.], grad_fn=<PowBackward0>)


In [35]:
# o = (1/2)sum(y) = (1/2)*sum(x^2)
o = (1/2)*sum(y) # (1/2)*(4+16) = 10
print("o =", o)

o = tensor(10., grad_fn=<MulBackward0>)


In [36]:
# backward
# türevler, gradientler hesaplanır
o.backward() # o'nun x'e göre türevi (ilk eleman x )

In [37]:
print("gradients:", x.grad) # türev x olarak hesaplanmıştı. x yerine 2 ve 4 değerlerini koyarsak sonuç 2 ve 4 olur

gradients: tensor([2., 4.])


In [ ]:
# türev hesaplayacağımız için variable veri tipini kullanacağız